apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-mcp-data-pvc
  labels:
    app: workspace-mcp
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
