apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kagent-outpost-token
  namespace: kagent
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: kagent-outpost-token
  data:
    - secretKey: token
      remoteRef:
        key: kagent-outpost-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-outpost-kagent
  namespace: kagent
  labels:
    app: authentik-outpost-kagent
    app.kubernetes.io/name: authentik-outpost-kagent
    app.kubernetes.io/instance: kagent
    app.kubernetes.io/component: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentik-outpost-kagent
  template:
    metadata:
      labels:
        app: authentik-outpost-kagent
        app.kubernetes.io/name: authentik-outpost-kagent
        app.kubernetes.io/instance: kagent
        app.kubernetes.io/component: proxy
        policy-type: "app"
    spec:
      containers:
        - name: outpost
          image: ghcr.io/goauthentik/proxy:2025.10.3
          env:
            - name: AUTHENTIK_HOST
              value: https://auth.seyzahl.com
            - name: AUTHENTIK_INSECURE
              value: "false"
            - name: AUTHENTIK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kagent-outpost-token
                  key: token
          volumeMounts:
            - name: sessions
              mountPath: /dev/shm
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: https
              containerPort: 9443
              protocol: TCP
            - name: metrics
              containerPort: 9300
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /outpost.goauthentik.io/ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /outpost.goauthentik.io/ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: sessions
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-outpost-kagent
  namespace: kagent
  labels:
    app: authentik-outpost-kagent
    app.kubernetes.io/name: authentik-outpost-kagent
    app.kubernetes.io/instance: kagent
    app.kubernetes.io/component: proxy
spec:
  selector:
    app: authentik-outpost-kagent
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: http
      port: 9000
      targetPort: http
      protocol: TCP
    - name: https
      port: 9443
      targetPort: https
      protocol: TCP
    - name: metrics
      port: 9300
      targetPort: metrics
      protocol: TCP
