apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  releaseName: external-secrets
  targetNamespace: external-secrets
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.18.2  # Use the latest version (chart version now matches app version)
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: false  # Since you're managing CRDs separately
    # Add this to ensure compatibility
    webhook:
      create: true
    certController:
      create: true

  install:
    createNamespace: true
  upgrade:
    # Force recreation of resources if needed
    force: true
