apiVersion: v1
data:
    ClientID: ENC[AES256_GCM,data:Yo1lJSP13fvRNfzFx0X1Ik0b47kPeV7RBx0r0HsK1jll0DcWUoP5ow==,iv:UoXS7xaJCc7ELR4RhHLNZBx6OCNP3tzbm4BYTPzQbOA=,tag:DX3W192NQeLKScm3jwhEtg==,type:str]
    ClientSecret: ENC[AES256_GCM,data:/Pj3shbvEwQ4wwmxaGoHy6NVwkmSQ0vC5MZ70XpzM17m5hEq,iv:tfFCpEItQ7ui9TaZc6PgSx+jqeV42o1ONSFjp1ek/eo=,tag:2s/IQvFfpQEda5Ij/oZWHg==,type:str]
kind: Secret
metadata:
    name: azure-creds
    namespace: external-secrets
sops:
    age:
        - recipient: age17qckp96wh2mzrd3dge9jrt6hudt40ltj2rgfqk42jgugjq9a94nqv6erff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bzFTVGxqQ0U5b2FWaXJF
            bUhDNDc4NWZrdGtVM3lIWHoyN2FzNTBYNmljCjBkVGVrU25lQ0I3YVV6SXpSQ0ky
            NEF3VGlaWHRKQUZYSU5Ud3JLUk1EYTAKLS0tIDRIZkcwdjd1OEEzeUM0MnEwc2JQ
            SXlTWVd3b0tpNnJQa0tHTnU3SHZxUmMKFr7NVmtQWkICfBIMGnd3w2M/LlKvwZMI
            DP4jaOS0KN6DqyOt4TgQelPOrlConYtm/G62m2Rj70ODHPTLBJnbZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T07:46:11Z"
    mac: ENC[AES256_GCM,data:5XrxuoeXNuU4Z6QUS6yPXgjJyEzgSHv2FIm4rY+pyd3sH2d1tSo70UkMcc8/nE4ORj0abNCRW1BmoCxFiuXfsuLrrtUMclbEdF7cWb+nECXU1LDaQHPpt+f//jL38nrA6bPn0iq//BZzDt2hKKhhgNZ8k41ZWcvBETvQmKrh20k=,iv:y54YjPwHqtvnU/mjn4A7S0CFMQEr7tYqGWQklzTKGO0=,tag:pIzQK8lQlJSs1j7/RQ7z5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
