apiVersion: v1
data:
    ClientID: ENC[AES256_GCM,data:ChbGjUQYGdag2F8kfnAV0g7osnsBKXDztPqtvdPnavKJd/Y3FSLlPJlLZ9l0++8k,iv:2ZBSC0PR4wRF12ulyxd3UwTcPZXWM8YWMIK4CBO1lZU=,tag:qNXaOwWQjcq4kXyobwnOMw==,type:str]
    ClientSecret: ENC[AES256_GCM,data:065Q4GVkbQ7MOqnSld+tP56iU8sPWsuiWdOzZRIFVb3HMQJzrPNeqj8J5cx3DtFPzUb9K4cV6P0=,iv:s7GJ0Zxqiq7LERK2PupiE83K/jl2AlWSsSUi2QFGEw0=,tag:wWniyf/EUceiicecj1SUUA==,type:str]
kind: Secret
metadata:
    name: azure-creds
    namespace: external-secrets
sops:
    age:
        - recipient: age17qckp96wh2mzrd3dge9jrt6hudt40ltj2rgfqk42jgugjq9a94nqv6erff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bzFTVGxqQ0U5b2FWaXJF
            bUhDNDc4NWZrdGtVM3lIWHoyN2FzNTBYNmljCjBkVGVrU25lQ0I3YVV6SXpSQ0ky
            NEF3VGlaWHRKQUZYSU5Ud3JLUk1EYTAKLS0tIDRIZkcwdjd1OEEzeUM0MnEwc2JQ
            SXlTWVd3b0tpNnJQa0tHTnU3SHZxUmMKFr7NVmtQWkICfBIMGnd3w2M/LlKvwZMI
            DP4jaOS0KN6DqyOt4TgQelPOrlConYtm/G62m2Rj70ODHPTLBJnbZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T08:04:28Z"
    mac: ENC[AES256_GCM,data:DULYuFHw7XgTWF7BWNYUGggFLBHPSHL1UNQINCBDBcAcfQBj7hsMRMCDXRPrBdqmem91/hKqxkuIkR/JePm3lZ0VtVEFQcQBbNn9b7HobrFuMep9Ah2pOIi/BYNFeUYfIbDEm8Fe6mfT6LTvgnSjDi/3uOyfmo2aR1tVJOeai+E=,iv:PymZTHVrQGovhYACEb2r9fu4W0xnWdtprlkRym1xRa4=,tag:BgOXhzTvef+neZRyvyG+XA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
