apiVersion: v1
data:
    ClientID: ENC[AES256_GCM,data:spGYUKZ4Y22OIKsxM4IOBSMySADgjuX1YFscGySqsL4CWWPAKxJemLaZn4sJylfw/dAegTCpZOI=,iv:W7gKG61Ol68O0SFG9fod7Q2VCDHvXXUIIW7DlCsrI6w=,tag:3bIY9UfEJwTJsT2GOgLu2w==,type:str]
    ClientSecret: ENC[AES256_GCM,data:D/6am58zFpCcSHG3KVDqvwpJcqpnjoTrAhriMCc1Tsuab8+Fy3gR/Gi7oQ381rVL,iv:1qxjwtwKc7rcPgMksVCcOPTKTRgR/A6gHKvHYJomxhs=,tag:8GGchICbnTA3EuJGgORoqQ==,type:str]
kind: Secret
metadata:
    name: azure-creds
    namespace: external-secrets
sops:
    age:
        - recipient: age17qckp96wh2mzrd3dge9jrt6hudt40ltj2rgfqk42jgugjq9a94nqv6erff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bzFTVGxqQ0U5b2FWaXJF
            bUhDNDc4NWZrdGtVM3lIWHoyN2FzNTBYNmljCjBkVGVrU25lQ0I3YVV6SXpSQ0ky
            NEF3VGlaWHRKQUZYSU5Ud3JLUk1EYTAKLS0tIDRIZkcwdjd1OEEzeUM0MnEwc2JQ
            SXlTWVd3b0tpNnJQa0tHTnU3SHZxUmMKFr7NVmtQWkICfBIMGnd3w2M/LlKvwZMI
            DP4jaOS0KN6DqyOt4TgQelPOrlConYtm/G62m2Rj70ODHPTLBJnbZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T07:54:57Z"
    mac: ENC[AES256_GCM,data:INkzZNDxzLqHkoB1NR4Ms6+YhmQAylwgm+97I13yHrlSkQzuIxAll4/bOIuY1QVktktA6wX3pKv2b0Fjc44kYYPWgE4+F5rj67sb1+Rgjx42B3x6UZgpJu2DofWrmulW/S0xwxhirU+slpqEiBfIoHbPvbWdUtEHzgD2Hhvf76g=,iv:CNrr9fdA2r1pkGaSbaacLfsDnrr/SpVMa6R73IVxAZA=,tag:IaTUn/SkhY5273kbHD7/4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
