apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent
  namespace: kagent
spec:
  interval: 30m
  dependsOn:
    - name: kagent-crds
  chart:
    spec:
      chart: kagent
      sourceRef:
        kind: OCIRepository
        name: kagent
        namespace: kagent
      interval: 12h
  valuesFrom:
    - kind: Secret
      name: kagent-openai-api-key
      valuesKey: apiKey
      targetPath: providers.openAI.apiKey
  values:
    providers:
      default: openAI
