apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner-docker-cache
  namespace: forgejo-runner
spec:
  accessModes:
    - ReadWriteOnce
  # Use local-path (default) instead of NFS to enable overlay2 storage driver
  # overlay2 requires filesystem features (xattr, etc.) that NFS doesn't support
  resources:
    requests:
      storage: 50Gi
