apiVersion: v1
kind: Service
metadata:
  name: pai-memory-lb
  labels:
    app: pai-memory
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pai-memory.seyzahl.com
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: pai-memory
