apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-env
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: authentik-db-username
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: authentik-db-password
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: authentik-secret-key
