apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: private-apps
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: private-apps
  url: ssh://git@github.com/pedrotchang/homelab-private
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: private-apps
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: private-apps
  path: "./apps"
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
