apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: private-apps
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: private-apps
  url: ssh://git@github.com/pedrotchang/homelab-private
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: private-apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: apps
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: private-apps
  path: "./apps"
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |-
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: homepage
          namespace: homepage
        data:
          services.yaml: |

            - Professional:
              - N8N:
                    href: http://auto.seyzahl.com/
                    icon: n8n.png
              - AWS:
                    href: https://us-west-1.console.aws.amazon.com
                    icon: aws.png
              - Azure:
                    href: https://portal.azure.com/#home
                    icon: azure.png
              - T3-Live:
                    href: https://www.t3live.com/login
              - finviz:
                    href: https://finviz.com
              - Schwab:
                    href: https://www.schwab.com/

            - Admin:
              - PVE-Main:
                    href: https://192.168.5.12:8006/
                    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/proxmox.png
              - PVE:
                    href: https://192.168.6.42:8006/
                    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/proxmox.png
              - Truenas:
                    href: https://192.168.7.14
                    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/truenas-scale.png
              - Authentik:
                    href: https://auth.seyzahl.com
                    icon: authentik.png
              - Unifi:
                    href: https://unifi.ui.com
                    icon: unifi.png
              - Omni:
                    href: https://pedrotchang.omni.siderolabs.io/
                    icon: talos.png

            - Private:
              - Immich:
                    href: https://immich.seyzahl.com
                    icon: immich.png
              - Jellyfin:
                    href: http://jellyfin.seyzahl.com
                    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/jellyfin.png
              - JellySeerr:
                    href: http://192.168.4.208
                    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/jellyseerr.png
              - qBittorrent:
                    href: http://qbittorrent.seyzahl.com
                    icon: qbittorrent.png
              - Suwayomi:
                    href: https://suwayomi.seyzahl.com/library
                    icon: suwayomi.png
              - Gluetun:
                    href: http://gluetun.seyzahl.com
                    icon: gluetun.png

            - Developer:
              - Github:
                    href: https://github.com/pedrotchang
                    icon: github.png
                    description: GitHub
              - CloudFlare:
                    href: https://cloudflare.com/
                    icon: cloudflare.png
                    description: CloudFlare
              - Kubernetes:
                    href: https://kubernetes.io/docs/home/
                    icon: kubernetes.png
                    description: Kubernetes Docs
              - Claude:
                    href: https://claude.ai/new
                    description: Claude
                    icon: claude-ai.png

            - Read:
              - Linkding:
                    href: https://linkding.seyzahl.com
                    icon: linkding.png
              - Commafeed:
                    href: https://commafeed.seyzahl.com
                    icon: commafeed.png
              - Wallabag:
                    href: https://wallabag.seyzahl.com
                    icon: wallabag.png

            - Learn:
              - KubeCraft:
                    href: https://www.skool.com/kubecraft
                    icon: kubecraft.png
              - Boot.dev:
                    href: https://www.boot.dev/tracks/backend
              - Udemy:
                    href: https://www.udemy.com/
      target:
        kind: ConfigMap
        name: homepage
        namespace: homepage
