apiVersion: v1
kind: ConfigMap
metadata:
  name: rocket-chat-configmap
data:
  ROOT_URL: "https://rocket-chat.seyzahl.com"
  PORT: "3000"
  DEPLOY_PLATFORM: "homelab"
  NODE_OPTIONS: "--max-old-space-size=768"
  OVERWRITE_SETTING_Accounts_RegistrationForm: "Disabled"
