apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: apps-pool
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.8.200"
      stop: "192.168.8.220"
  serviceSelector:
    matchLabels:
      cilium-lb-pool: apps-pool
