---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: gateway-apps-pool
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.4.221"
      stop: "192.168.4.255"
  serviceSelector:
    matchLabels:
      cilium.io/gateway: "servarr"

