apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress-pool
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.8.190"
      stop: "192.168.8.199"
  serviceSelector:
    matchLabels:
      cilium.io/ingress: "true"
