apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-gotenberg
  labels:
    app: paperless-gotenberg
    policy-type: "app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-gotenberg
  template:
    metadata:
      labels:
        app: paperless-gotenberg
        policy-type: "app"
    spec:
      containers:
        - name: gotenberg
          image: gotenberg/gotenberg:8
          ports:
            - containerPort: 3000
          command:
            - "gotenberg"
            - "--chromium-disable-javascript=true"
            - "--chromium-allow-list=file:///tmp/.*"
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-gotenberg
  labels:
    app: paperless-gotenberg
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: paperless-gotenberg
