apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-container-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: PAPERLESS_DBUSER
      remoteRef:
        key: paperless-db-username
    - secretKey: PAPERLESS_DBPASS
      remoteRef:
        key: paperless-db-password
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: paperless-secret-key
    - secretKey: PAPERLESS_ADMIN_USER
      remoteRef:
        key: paperless-admin-user
    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: paperless-admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-gpt-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: PAPERLESS_API_TOKEN
      remoteRef:
        key: paperless-api-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel
  data:
    - secretKey: credentials.json
      remoteRef:
        key: paperless-cloudflare-tunnel
