apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  - namespace.yaml
  - deployment.yaml
  - secrets.yaml
  - service.yaml
  - storage.yaml
  - storage-nfs.yaml
  - migration-job.yaml
