apiVersion: batch/v1
kind: Job
metadata:
  name: n8n-data-migration
  namespace: n8n
spec:
  template:
    spec:
      containers:
      - name: migration
        image: busybox
        command: ["sh", "-c", "cp -r /source/* /destination/ && echo 'Migration completed successfully'"]
        volumeMounts:
        - name: old-data
          mountPath: /source
        - name: new-data
          mountPath: /destination
      volumes:
      - name: old-data
        persistentVolumeClaim:
          claimName: n8n-data-pvc
      - name: new-data
        persistentVolumeClaim:
          claimName: n8n-data-pvc-nfs
      restartPolicy: Never
