apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-pvc-nfs
  namespace: n8n
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 1Gi
