apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-outpost-token
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: homepage-outpost-token
  data:
    - secretKey: token
      remoteRef:
        key: homepage-outpost-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-outpost-homepage
  namespace: homepage
  labels:
    app: authentik-outpost-homepage
    app.kubernetes.io/name: authentik-outpost-homepage
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/component: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentik-outpost-homepage
  template:
    metadata:
      labels:
        app: authentik-outpost-homepage
        app.kubernetes.io/name: authentik-outpost-homepage
        app.kubernetes.io/instance: homepage
        app.kubernetes.io/component: proxy
        policy-type: "app"
    spec:
      containers:
        - name: outpost
          image: ghcr.io/goauthentik/proxy:2025.10.3
          env:
            - name: AUTHENTIK_HOST
              value: http://authentik.authentik.svc.cluster.local:9000
            - name: AUTHENTIK_INSECURE
              value: "true"
            - name: AUTHENTIK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homepage-outpost-token
                  key: token
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: https
              containerPort: 9443
              protocol: TCP
            - name: metrics
              containerPort: 9300
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /outpost.goauthentik.io/ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /outpost.goauthentik.io/ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-outpost-homepage
  namespace: homepage
  labels:
    app: authentik-outpost-homepage
    app.kubernetes.io/name: authentik-outpost-homepage
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/component: proxy
spec:
  selector:
    app: authentik-outpost-homepage
  ports:
    - name: http
      port: 9000
      targetPort: http
      protocol: TCP
    - name: https
      port: 9443
      targetPort: https
      protocol: TCP
    - name: metrics
      port: 9300
      targetPort: metrics
      protocol: TCP
