apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  # kubernetes.yaml: |
  #   mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/pedrotchang
        - KubeCraft:
            - abbr: KC
              href: https://www.skool.com/kubecraft
  services.yaml: |
    - seyzahl
        - Linkding
            href: http://linkding.seyzahl.com
            description: Linkding

        - Omni
            href: https://pedrotchang.omni.siderolabs.io/
            description: Omni

        - Grafana
            href: https://rw6q7h-pedrotchang.proxy-us.omni.siderolabs.io
            description: Grafana

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
