apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: n8n-mcp
  namespace: kmcp-system
spec:
  deployment:
    image: ghcr.io/pedrotchang/mcp/n8n:latest
    env:
      N8N_BASE_URL: "https://auto.seyzahl.com"
  transportType: "stdio"
