apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-mcp-secrets
  namespace: kmcp-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: n8n-mcp-secrets
  data:
    - secretKey: api-key
      remoteRef:
        key: n8n-mcp-api-key
