apiVersion: v1
kind: Service
metadata:
  name: servarr-radarr
  namespace: servarr
spec:
  selector:
    app: radarr
  ports:
    - port: 7878
      targetPort: 7878
      name: http
  type: ClusterIP
