apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: maybe-container-env
  namespace: maybe
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: maybe-secret-base
    - secretKey: POSTGRES_USER
      remoteRef:
        key: maybe-db-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: maybe-db-password
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: cloudflare-tunnel
#   namespace: maybe
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: azure-kv-store
#     kind: ClusterSecretStore
#   data:
#     - secretKey: credentials.json
#       remoteRef:
#         key: maybe-cloudflare-tunnel
