apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: servarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
      annotations:
        cilium.io/gateway: "true"
    spec:
      containers:
        - name: jellyfin
          image: linuxserver/jellyfin:10.10.7
          resources:
            limits:
              cpu: 3000m
              memory: 8Gi
            requests:
              cpu: 500m
              memory: 2Gi
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: jellyfin
            - name: media
              mountPath: /media
          ports:
            - containerPort: 8096
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: servarr-config-pvc-nfs
        - name: media
          persistentVolumeClaim:
            claimName: servarr-media-pvc-nfs
