apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: servarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
      annotations:
        cilium.io/gateway: "true"
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:10.10.7
          ports:
            - containerPort: 8096
              protocol: TCP
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: JELLYFIN_PublishedServerUrl
              value: "http://jellyfin.seyzahl.com"
            - name: JELLYFIN_DATA_DIR
              value: "/config"
            - name: JELLYFIN_CONFIG_DIR
              value: "/config/config"
            - name: JELLYFIN_LOG_DIR
              value: "/config/log"
            - name: JELLYFIN_CACHE_DIR
              value: "/config/cache"
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: jellyfin
            - name: media
              mountPath: /media
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 3000m
              memory: 8Gi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: servarr-config-pvc-nfs
        - name: media
          persistentVolumeClaim:
            claimName: servarr-media-pvc-nfs
        - name: tmp
          emptyDir: {}
