apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-data-pvc
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
