apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:qtBVIfyKjQeH9xYa/0u2O0bbpAVHRhM4USULk12JaJ4sSCtMbptr6OgkOBp2E9PjD3TO7nWWzUOXLqvV4sXQ7X8EsFJBjk1EU8RIshx/sUUa7dMXYOrE1lY8nV1Uk3w2KWxwkz9t0wtZpr/SaVS/O5t8/rTUPNeKhw7N9PoBAvUwjV5eFDJBbYNET+fR/qTvVn/ik+BLQ0rjRrsmsmmEhymRXXjSUrU4KD2nURaOscKWfP1bjKziluad7BGs992Crb9ss2mmOdxGahJdPhsJez8gsWGcu4vl,iv:IJzmDHPtwQA2V+WZFxcsQmi7QRrNL/skggu0CYKP9O4=,tag:EFuS//cd1/Oj+XJ++5GGYg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17qckp96wh2mzrd3dge9jrt6hudt40ltj2rgfqk42jgugjq9a94nqv6erff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYXgrVlczZk9pUGZzR3dh
            UnIzK2NJcXZ1cHB6Vm9URkpCbWN6UEwzSGlzCmtpNXhMTG1Kc2gvUzNZYmpTdGY1
            eHhkQUZ6aGg3dk9OS3pVSFdQVzVDbU0KLS0tIEpsREVkMWt1MTYwckFEVUU0cjdE
            V0Q3TzlpRHQxNThWNlM1WWNxUFR3TEUK44euu9v9UjZLvxrUkeuwRjsRTCKW6lNW
            tj/xnD3uvme0SgY+PhHMt0jPQH7TQ0J5zVpvaNit3YSsNDOl0QdUtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T08:26:04Z"
    mac: ENC[AES256_GCM,data:XKQD6U4LY8aFJNMqMWSldH/Cfcr1KOSUroVvU0gYHvv74px3vk0Mu6SQju5WR1DBIEpG4thRpQbSHX463J1dIUn+Fn2Ixshwp3oau0zUgCgotlNU263RYfEgCcOkBIMtNjL+kvEL/kOkrZAakJBVuM3xqK/y57WpT9jbSrDQ2ok=,iv:/YeQMWdlo/pTK9yfiRfgnB3+pQ++gTRL2+2/FO5tf2c=,tag:HO+nEMtvHXO/Ab/VLCdvnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
