apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:rRiUxrwOS8acCzIhQPFFcn4k2M+FMfScOPfKmoo+XcyUeBZjb2pOVYoJfZf3IFw1LsGFY/KeQYVDrglRHtwmGTZnQ12LsyoqnnEhFhpYCN2Nn4iQ4mXEJwFqcxP3vZPf6z67Me7ju7QpbKHdOSXkLNZXWfjGyUMe321aVW4bs+fK8vbzcNQccMoFI6TcfmLkDCCKwkQG/4FFKSn4ZN/VKdBPOLf5i8uWbQRsHfaA+88OIPzYcC1LS2SGrFcJvmnK8Ng8kSQNsvzKq9XH8gXmomx1K1HMURH4,iv:io55K3Ku3ETMIIXHtr2gjtKIjGh4i9EsIgIKdp7d/Hk=,tag:YwBsfyoHVpmulfNgkDcqTw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17qckp96wh2mzrd3dge9jrt6hudt40ltj2rgfqk42jgugjq9a94nqv6erff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MXFya0ovdmxRMXBlNFFO
            RFE5SXZiaEkrWUlRQTJRSk5MQkRuaE9RaFFRCkNtbVdCRkh4OFo2NDJCSEVtNDNV
            d3U4K1ZxRkI2WERsbml5Y0w2Y0hqcTQKLS0tIGMvNHBJeEY2T1FNYjNxRFNROUJo
            RUlvVE03RUIzY0FpTm9GcGhnU0p4N1UKJ/LAREecIby5u9HqJdqA15js2/L3SGbK
            EWEqxPXbgSi9jDQLl7yttFEEMBuqaTkNuEidAow7lb/Oydh67WXIDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T22:37:25Z"
    mac: ENC[AES256_GCM,data:IF7cZmJLgMos/I+1w/sVAzsDWcLVX5OTNQC4tcLrqsAyj9l1jF2nMYxIm2AESFgxFUjW+Iz2OclWw6KoelRtAgVhJAQmVEzWxlEZTsHdQY+beQPmZOXbZahqOsvvvRQXLgSiTJXpBH6BwPm7RkqxMozXbSRGMN4HP1U2li4iVTM=,iv:ix5UFr1L6N9ZFk3LDaJJHTWHzhnxIlSzzfnjUKssAaY=,tag:9UbC3VsezcA9gRs4D68gGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
