apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: csi-driver-iscsi
  namespace: storage
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: democratic-csi
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    # Allow all egress - CSI drivers need full API access
    - {}
