apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-iscsi
  namespace: storage
spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: democratic-csi
      version: "0.14.7"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: storage
  valuesFrom:
    - kind: ConfigMap
      name: csi-driver-iscsi-values
    - kind: Secret
      name: truenas-iscsi-driver-config
      valuesKey: driver-config.yaml
      targetPath: driver.config
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
