apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-iscsi
  namespace: storage
  annotations:
    meta.helm.sh/release-name: csi-driver-iscsi
    meta.helm.sh/release-namespace: storage
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:0.14.*
  labels:
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: storage

spec:
  interval: 1h
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: csi-driver-nfs
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # Secrets configuration
    secrets:
      truenas:
        create: false
        apiKeySecret: "truenas-api-credentials"

    # Image configuration with specific versions for security
    image:
      baseRepo: registry.k8s.io
      nfs:
        repository: registry.k8s.io/sig-storage/nfsplugin
        tag: v4.11.0
        pullPolicy: IfNotPresent
      csiProvisioner:
        repository: registry.k8s.io/sig-storage/csi-provisioner
        tag: v5.2.0
        pullPolicy: IfNotPresent
      csiResizer:
        repository: registry.k8s.io/sig-storage/csi-resizer
        tag: v1.13.1
        pullPolicy: IfNotPresent
      csiSnapshotter:
        repository: registry.k8s.io/sig-storage/csi-snapshotter
        tag: v8.2.0
        pullPolicy: IfNotPresent
      livenessProbe:
        repository: registry.k8s.io/sig-storage/livenessprobe
        tag: v2.15.0
        pullPolicy: IfNotPresent
      nodeDriverRegistrar:
        repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
        tag: v2.13.0
        pullPolicy: IfNotPresent
      externalSnapshotter:
        repository: registry.k8s.io/sig-storage/snapshot-controller
        tag: v8.2.0
        pullPolicy: IfNotPresent
      
    serviceAccount:
      create: true
      controller: csi-nfs-controller-sa
      node: csi-nfs-node-sa
      annotations:
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/component: storage
    rbac:
      create: true
      name: nfs

    # Driver configuration
    driver:
      name: nfs.csi.k8s.io
      mountPermissions: 0750

    # Feature flags
    feature:
      enableFSGroupPolicy: true
      enableInlineVolume: false
      propagateHostMountOptions: false

    kubeletDir: /var/lib/kubelet
