apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-iscsi-driver-config
  namespace: storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: truenas-iscsi-driver-config
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-api-iscsi
          instance_id: truenas-iscsi
          httpConnection:
            protocol: http
            host: 192.168.7.14
            port: 80
            apiKey: "{{ .apiKey }}"
            allowInsecure: false
          zfs:
            datasetParentName: "tank/k8s/iscsi/volumes"
            detachedSnapshotsDatasetParentName: "tank/k8s/iscsi/snapshots"
            zvolCompression: ""
            zvolDedup: ""
            zvolEnableReservation: false
            zvolBlocksize: "16K"
          iscsi:
            targetPortal: "192.168.7.14:3260"
            targetPortals: []
            interface: ""
            namePrefix: "csi-"
            nameSuffix: "-tachtit"
            targetGroups:
              - targetGroupPortalGroup: 1
                targetGroupInitiatorGroup: 1
                targetGroupAuthType: None
            extentInsecureTpc: true
            extentXenCompat: false
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 4096
            extentRpm: "SSD"
            extentAvailThreshold: 0
  data:
    - secretKey: apiKey
      remoteRef:
        key: truenas-api-key
