apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: servarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
      annotations:
        cilium.io/gateway: "true"
    spec:
      # Only keep fsGroup for NFS permissions
      securityContext:
        fsGroup: 1000
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:1.37.0
          ports:
            - containerPort: 9696
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
            - name: UMASK
              value: "002"
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: prowlarr
          # Remove container securityContext
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: servarr-config-pvc-nfs
