apiVersion: v1
kind: Service
metadata:
  name: servarr-prowlarr
  namespace: servarr
spec:
  selector:
    app: prowlarr
  ports:
    - port: 9696
      targetPort: 9696
      name: http
  type: ClusterIP
