apiVersion: mcp.kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: github-mcp
  namespace: github-mcp
spec:
  description: GitHub MCP server for PR analysis and upgrade guide generation
  transport: stdio
  env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-mcp-secrets
          key: token
    - name: GITOPS_REPO
      value: "pedrotchang/homelab"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
