apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: democratic-csi
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - secrets.yaml

configMapGenerator:
  - name: democratic-csi-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
