apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-iscsi
  namespace: storage
  annotations:
    meta.helm.sh/release-name: csi-driver-iscsi
    meta.helm.sh/release-namespace: storage
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:0.14.*
  labels:
    app.kubernetes.io/name: csi-driver-iscsi
    app.kubernetes.io/instance: csi-driver-iscsi
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: storage
    app.kubernetes.io/version: "0.14.7"
    production-grade: "true"
    security-hardened: "true"

spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: democratic-csi
      version: "0.14.7"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    force: true
  uninstall:
    keepHistory: false

  valuesFrom:
    - kind: ConfigMap
      name: democratic-csi-values
