csiDriver:
  name: "org.democratic-csi.iscsi"
  attachRequired: true
  storageCapacity: true
  fsGroupPolicy: "File"

controller:
  enabled: true
  strategy: deployment
  replicas: 2
  driver:
    env:
      - name: api_key
        valueFrom:
          secretKeyRef:
            name: truenas-api-credentials
            key: api-key
      # - name: encryption_key
      #   valueFrom:
      #     secretKeyRef:
      #       name: csi-driver-iscsi-secret
      #       key: encryption_key
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: 50m
        memory: 64Mi
        ephemeral-storage: 100Mi


  externalAttacher:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
        ephemeral-storage: 100Mi
      limits:
        memory: 200Mi
        ephemeral-storage: 200Mi

  externalResizer:
    enabled: true
    image: registry.k8s.io/sig-storage/csi-resizer:v1.13.1
    logLevel: 2
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: 20m
        memory: 32Mi
        ephemeral-storage: 100Mi

  externalSnapshotter:
    enabled: true
    image: registry.k8s.io/sig-storage/csi-snapshotter:v8.2.0
    logLevel: 2
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: 20m
        memory: 32Mi
        ephemeral-storage: 100Mi

  livenessProbe:
    enabled: true
    image: registry.k8s.io/sig-storage/livenessprobe:v2.15.0
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 100Mi
      requests:
        cpu: 10m
        memory: 16Mi
        ephemeral-storage: 50Mi

      # Pod configuration
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - csi-driver-iscsi
            topologyKey: kubernetes.io/hostname

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule

  priorityClassName: system-cluster-critical

storageClasses:
  - name: iscsi
    defaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4
      detachedVolumesFromSnapshots: "false"
    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

csiProxy:
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
      ephemeral-storage: 100Mi
    limits:
      memory: 150Mi
      ephemeral-storage: 200Mi

node:
  enabled: true
  hostPID: true
  strategy: deployment
  driver:
    env:
    - name: api_key
      valueFrom:
        secretKeyRef:
          name: truenas-api-credentials
          key: truenas-api-key
    # - name: encryption_key
    #   valueFrom:
    #     secretKeyRef:
    #       name: csi-driver-iscsi-secret
    #       key: encryption_key

    # iSCSI specific configuration
    iscsiDirHostPath: /etc/iscsi
    iscsiDirHostPathType: DirectoryOrCreate

    # Resource configuration
    resources:
      limits:
        cpu: 400m
        memory: 384Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: 40m
        memory: 48Mi
        ephemeral-storage: 100Mi


  # Driver registrar sidecar
  driverRegistrar:
    enabled: true
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
    logLevel: 2
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 100Mi
      requests:
        cpu: 10m
        memory: 16Mi
        ephemeral-storage: 50Mi

  # Liveness probe sidecar
  livenessProbe:
    enabled: true
    image: registry.k8s.io/sig-storage/livenessprobe:v2.15.0
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 100Mi
      requests:
        cpu: 10m
        memory: 16Mi
        ephemeral-storage: 50Mi

  # Pod configuration
  podSecurityContext:
    runAsNonRoot: false  # Required for iSCSI operations
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: true  # Required for iSCSI operations
    capabilities:
      add:
        - SYS_ADMIN  # Required for iSCSI mount operations
      drop:
        - ALL
    readOnlyRootFilesystem: true
    privileged: false
    seccompProfile:
      type: RuntimeDefault

  tolerations:
    - operator: Exists

  priorityClassName: system-node-critical

driver:
  config:
    driver: freenas-api-iscsi
    instance_id: "iscsi-prod"
    httpConnection:
      protocol: https
      host: 192.168.7.14
      port: 443
      allowInsecure: true
      apiVersion: 2
    zfs:
      datasetParentName: "tank/k8s/volumes"
      detachedSnapshotsDatasetParentName: "tank/k8s/snapshots"
      zvolCompression:
      zvolDedup:
      zvolEnableReservation: false
      zvolBlocksize:
    iscsi:
      targetPortal: "192.168.7.14:3260"
      interface:
      namePrefix: csi-
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
          targetGroupAuthGroup:
      extentInsecureTpc: true
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0
