csiDriver:
  name: "org.democratic-csi.iscsi"

storageClasses:
- name: truenas-iscsi-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4
  mountOptions: []

# Remove volumeSnapshotClasses until snapshot CRDs are installed
# volumeSnapshotClasses:
# - name: truenas-iscsi-csi
#   parameters: {}

node:
  hostPID: true
  driver:
    extraEnv:
    - name: ISCSIADM_EXEC_TIMEOUT
      value: "5"
    - name: ISCSIADM_EXEC_RETRY
      value: "10"
    - name: ISCSIADM_HOST_STRATEGY
      value: nsenter
    - name: ISCSIADM_HOST_PATH
      value: /usr/local/sbin/iscsiadm
    iscsiDirHostPath: /usr/local/etc/iscsi
    iscsiDirHostPathType: ""
  cleanup:
    image:
      repository: busybox
      tag: "1.36"

controller:
  driver:
    image:
      repository: democraticcsi/democratic-csi
      tag: "v1.9.3"
    logLevel: debug
    extraEnv:
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"

driver:
  config:
    driver: freenas-api-iscsi
    instance_id:
    httpConnection:
      protocol: https
      host: 192.168.7.14
      port: 443
      apiKeySecret:
        secretName: truenas-api-credentials
        secretKey: api-key
      allowInsecure: true
      timeout: 30000
      
    zfs:
      cli:
        sudoEnabled: true
        
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
        
      datasetParentName: "tank/k8s/volumes"
      detachedSnapshotsDatasetParentName: "tank/k8s/snapshots"
      
      zvolCompression: ""
      zvolDedup: ""
      zvolVolblocksize: ""
      
    iscsi:
      targetPortal: "192.168.7.14:3260"
      targetPortals: []
      
      nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      namePrefix: "csi-"
      nameSuffix: ""
      
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None

      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0
