apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt
  namespace: newt
spec:
  interval: 30m
  chart:
    spec:
      chart: newt
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: fossorial
        namespace: newt
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: newt-values
