apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newt-auth-keys
  namespace: newt
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: endpoint-key
      remoteRef:
        key: newt-endpoint-key
    - secretKey: id-key
      remoteRef:
        key: newt-id-key
    - secretKey: secret-key
      remoteRef:
        key: newt-secret-key
