apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lux-api-claude-config
  namespace: lux-api
spec:
  storageClassName: truenas-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
