apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr

resources:
  - namespace.yaml
  - repository.yaml
  - storage.yaml
  - gateway.yaml       # Gateway API configuration
  - routes.yaml        # HTTPRoutes
  - release.yaml

configMapGenerator:
  - name: servarr-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

