apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr

resources:
  - namespace.yaml
  - storage.yaml
  - gateway.yaml
  - routes.yaml
  - jellyfin/
  - prowlarr/
  - radarr/
  - sonarr/
  - qbittorrent/
