---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: servarr
  namespace: servarr
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: servarr
      version: ">=0.1.0"
      sourceRef:
        kind: HelmRepository
        name: kubitodev
        namespace: servarr
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: servarr-values
      valuesKey: values.yaml
