apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-media-pvc-nfs
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 4Ti


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-config-pvc-nfs
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 100Gi
