jellyfin:
  enabled: true
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/jellyfin
    tag: "10.10.7"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8096
    annotations:
      cilium.io/gateway: "true"
  persistence:
    config:
      enabled: true
      storageClass: truenas-nfs
      accessmode: ReadWriteOnce
      size: 2Gi
    media:
      enabled: true
      storageClass: truenas-nfs
      accessmode: ReadWriteOnce
      size: 4Ti
  podSecurityContext:
    runAsUser: 65534
    runAsGroup: 65534
  securityContext:
    capabilities:
      add:
        - "SYS_ADMIN"
      drop:
        - "ALL"
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 3000m
      memory: 8Gi

sonarr:
  enabled: true
  replicaCount: 1
  podAnnotations:
    cilium.io/gateway: "true"
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: "4.0.15"
    pullPolicy: IfNotPresent
  deployment:
    strategy:
      type: Recreate
  service:
    type: ClusterIP
    port: 80
  env:
    PUID: 1000
    PGID: 1000
    TZ: "America/Los_Angeles"
    UMASK: "002"
  persistence:
    enabled: true
    path: tv
    storageClass: truenas-nfs
    accessMode: ReadWriteOnce
    size: 800Mi

qbittorrent:
  enabled: true
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/qbittorrent
    tag: "5.1.2"
    pullPolicy: IfNotPresent
  deployment:
    strategy:
      type: Recreate
  podAnnotations:
    cilium.io/gateway: "true"
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFileSystem: True
    runAsNonRoot: true
    runAsUser: 1000
  service:
    web:
      type: ClusterIP
      port: 8080
    bt:
      type: ClusterIP
      port: 6881
  env:
    PUID: 1000
    PGID: 1000
    TZ: "America/Los_Angeles"
  persistence:
    enabled: true
    path: downloads
    storageClass: truenas-nfs
    accessMode: ReadWriteOnce
    size: 1Ti

prowlarr:
  enabled: true
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/prowlarr
    tag: "1.37.0"
    pullPolicy: IfNotPresent
  podAnnotations:
    cilium.io/gateway: "true"
  deployment:
    strategy:
      type: Recreate
  service:
    type: ClusterIP
    port: 9696
  env:
    PUID: 1000
    PGID: 1000
    TZ: "America/Los_Angeles"
    UMASK: "002"
  persistence:
    enabled: true
    storageClass: truenas-nfs
    accessMode: ReadWriteOnce
    size: 1Gi

flaresolverr:
  enabled: true
  image:
    repository: ghcr.io/flaresolverr/flaresolverr
    tag: "v3.3.25"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8191

jellyseerr:
  enabled: true
  replicaCount: 1
  image:
    repository: docker.io/fallenbagel/jellyseerr
    tag: "2.3.0"
    pullPolicy: IfNotPresent
  deployment:
    strategy:
      type: Recreate
  podAnnotations:
    cilium.io/gateway: "true"
  podSecurityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    privileged: false
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  service:
    type: ClusterIP
    port: 5055
  persistence:
    enabled: true
    storageClass: truenas-nfs
    accessMode: ReadWriteOnce
    size: 800Mi

bazarr:
  enabled: true
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: "1.5.3-development"
    pullPolicy: IfNotPresent
  deployment:
    strategy:
      type: Recreate
  podAnnotations:
    cilium.io/gateway: "true"
  service:
    type: ClusterIP
    port: 6767
  env:
    PUID: 1000
    PGID: 1000
    TZ: "America/Los_Angeles"
  persistence:
    enabled: true
    storageClass: truenas-nfs
    accessMode: ReadWriteOnce
    size: 1Gi

radarr:
  enabled: true
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/radarr
    tag: "5.26.2"
    pullPolicy: IfNotPresent
  deployment:
    strategy:
      type: Recreate
  podAnnotations:
    cilium.io/gateway: "true"
  service:
    type: ClusterIP
    port: 7878
  env:
    PUID: 1000
    PGID: 1000
    TZ: "America/Los_Angeles"
    UMASK: "002"
  persistence:
    enabled: true
    path: movies
    storageClass: truenas-nfs
    accessMode: ReadWriteOnce
    size: 1Gi

lidarr:
  enabled: false

readarr:
  enabled: false

cleanuperr:
  enabled: false
