# Global settings
global:
  env:
    PUID: 1000
    PGID: 1000
    TZ: "America/Los_Angeles"

# Jellyfin - Media Server
jellyfin:
  enabled: true
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8096
  persistence:
    config:
      enabled: true
      existingClaim: servarr-config-pvc-nfs
      subPath: jellyfin
    media:
      enabled: true
      existingClaim: servarr-media-pvc-nfs
      mountPath: /media
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi

# Prowlarr - Indexer Manager
prowlarr:
  enabled: true
  persistence:
    config:
      enabled: true
      existingClaim: servarr-config-pvc-nfs
      subPath: prowlarr
  service:
    type: ClusterIP
    port: 9696

# Sonarr - TV Show Manager
sonarr:
  enabled: true
  persistence:
    config:
      enabled: true
      existingClaim: servarr-config-pvc-nfs
      subPath: sonarr
    tv:
      enabled: true
      existingClaim: servarr-media-pvc-nfs
      mountPath: /tv
      subPath: tv
    downloads:
      enabled: true
      existingClaim: servarr-downloads-pvc-nfs
      mountPath: /downloads
  service:
    type: ClusterIP
    port: 8989

# Radarr - Movie Manager
radarr:
  enabled: true
  persistence:
    config:
      enabled: true
      existingClaim: servarr-config-pvc-nfs
      subPath: radarr
    movies:
      enabled: true
      existingClaim: servarr-media-pvc-nfs
      mountPath: /movies
      subPath: movies
    downloads:
      enabled: true
      existingClaim: servarr-downloads-pvc-nfs
      mountPath: /downloads
  service:
    type: ClusterIP
    port: 7878

# Lidarr - Music Manager
lidarr:
  enabled: true
  persistence:
    config:
      enabled: true
      existingClaim: servarr-config-pvc-nfs
      subPath: lidarr
    music:
      enabled: true
      existingClaim: servarr-media-pvc-nfs
      mountPath: /music
      subPath: music
    downloads:
      enabled: true
      existingClaim: servarr-downloads-pvc-nfs
      mountPath: /downloads
  service:
    type: ClusterIP
    port: 8686

# qBittorrent - Download Client
qbittorrent:
  enabled: true
  persistence:
    config:
      enabled: true
      existingClaim: servarr-config-pvc-nfs
      subPath: qbittorrent
    downloads:
      enabled: true
      existingClaim: servarr-downloads-pvc-nfs
      mountPath: /downloads
  service:
    type: ClusterIP
    port: 8080

# FlareSolverr - Cloudflare bypass
flaresolverr:
  enabled: true
  service:
    type: ClusterIP
    port: 8191

# Jellyseerr - Request Management
jellyseerr:
  enabled: true
  persistence:
    config:
      enabled: true
      existingClaim: servarr-config-pvc-nfs
      subPath: jellyseerr
  service:
    type: ClusterIP
    port: 5055

# Tailscale Integration (Optional)
# tailscale:
#   sidecar:
#     enabled: true
#     authSecret: "tailscale-auth"  # Create this secret with your auth key
