jellyfin:
  enabled: true
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/jellyfin
    tag: "10.10.7"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8096
    annotations:
      cilium.io/gateway: "true"
  persistence:
    config:
      enabled: false
      existingClaim: servarr-config-pvc-nfs
      subPath: jellyfin
    media:
      enabled: false
      existingClaim: servarr-media-pvc-nfs
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi

sonarr:
  enabled: true
  replicaCount: 1
  podAnnotations:
    cilium.io/gateway: "true"
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: "4.0.15"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8989
  env:
    PUID: 1000
    PGID: 1000
    TZ: "America/Los_Angeles"
    UMASK: "002"
  persistence:
    enabled: false
    path: tv
    storageClass: truenas-nfs
    existingClaim: servarr-config-pvc-nfs

qbittorrent:
  enabled: true
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/qbittorrent
    tag: "5.1.2"
    pullPolicy: IfNotPresent
  podAnnotations:
    cilium.io/gateway: "true"
  service:
    web:
      type: ClusterIP
      port: 8080
    bt:
      type: ClusterIP
      port: 6881
  env:
    PUID: 1000
    PGID: 1000
    TZ: "America/Los_Angeles"
  persistence:
    enabled: false
    path: downloads
    storageClass: truenas-nfs
    existingClaim: servarr-config-pvc-nfs

prowlarr:
  enabled: true
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/prowlarr
    tag: "1.37.0"
    pullPolicy: IfNotPresent
  podAnnotations:
    cilium.io/gateway: "true"
  service:
    type: ClusterIP
    port: 9696
  env:
    PUID: 1000
    PGID: 1000
    TZ: "America/Los_Angeles"
    UMASK: "002"
  persistence:
    enabled: false
    storageClass: truenas-nfs
    existingClaim: servarr-config-pvc-nfs

flaresolverr:
  enabled: true
  image:
    repository: ghcr.io/flaresolverr/flaresolverr
    tag: "v3.3.25"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8191

jellyseerr:
  enabled: true
  replicaCount: 1
  image:
    repository: docker.io/fallenbagel/jellyseerr
    tag: "2.3.0"
    pullPolicy: IfNotPresent
  podAnnotations:
    cilium.io/gateway: "true"
  service:
    type: ClusterIP
    port: 5055
  persistence:
    enabled: true
    storageClass: truenas-nfs
    existingClaim: servarr-config-pvc-nfs

bazarr:
  enabled: true
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: "1.5.3-development"
    pullPolicy: IfNotPresent
  podAnnotations:
    cilium.io/gateway: "true"
  service:
    type: ClusterIP
    port: 6767
  env:
    PUID: 1000
    PGID: 1000
    TZ: "America/Los_Angeles"
  persistence:
    enabled: true
    storageClass: truenas-nfs
    existingClaim: servarr-config-pvc-nfs

radarr:
  enabled: true
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/radarr
    tag: "5.26.2"
    pullPolicy: IfNotPresent
  podAnnotations:
    cilium.io/gateway: "true"
  service:
    type: ClusterIP
    port: 7878
  env:
    PUID: 1000
    PGID: 1000
    TZ: "America/Los_Angeles"
    UMASK: "002"
  persistence:
    enabled: false
    path: movies
    storageClass: truenas-nfs
    existingClaim: servarr-config-pvc-nfs

lidarr:
  enabled: false

readarr:
  enabled: false

cleanuperr:
  enabled: false
