apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kmcp-crds
  namespace: kmcp-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kmcp-crds
      sourceRef:
        kind: HelmRepository
        name: kmcp
        namespace: kmcp-system
      interval: 12h
