apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

resources:
  - namespace.yaml
  - repository.yaml
  - secrets.yaml
  - release.yaml
  # - pdb.yaml
  # - vpa.yaml

configMapGenerator:
  - name: csi-driver-nfs-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

generatorOptions:
  disableNameSuffixHash: false

labels:
- pairs:
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: storage
  includeSelectors: true

commonLabels:
  app.kubernetes.io/name: csi-driver-nfs
  app.kubernetes.io/part-of: storage
