apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: storage
  annotations:
    meta.helm.sh/release-name: csi-driver-nfs
    meta.helm.sh/release-namespace: storage
  labels:
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: storage

spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: csi-driver-nfs
      version: "4.11.0"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
