apiVersion: v1
kind: ConfigMap
metadata:
  name: postiz-api-proxy-config
  namespace: postiz
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 8080;

        location /api/ {
          # Strip /api prefix and proxy to backend
          rewrite ^/api/(.*)$ /$1 break;
          proxy_pass http://postiz-backend.postiz.svc.cluster.local:3000;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postiz-api-proxy
  namespace: postiz
  labels:
    app: postiz-api-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postiz-api-proxy
  template:
    metadata:
      labels:
        app: postiz-api-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
      volumes:
        - name: config
          configMap:
            name: postiz-api-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: postiz-api-proxy
  namespace: postiz
  labels:
    app: postiz-api-proxy
spec:
  selector:
    app: postiz-api-proxy
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
