apiVersion: v1
kind: Service
metadata:
  name: postiz-backend
  namespace: postiz
  labels:
    app: postiz-backend
spec:
  selector:
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/name: postiz-app
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
