apiVersion: apps/v1
kind: Deployment
metadata:
  name: postiz-redis
  namespace: postiz
  labels:
    app: postiz-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postiz-redis
  template:
    metadata:
      labels:
        app: postiz-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: postiz-redis
  namespace: postiz
  labels:
    app: postiz-redis
spec:
  selector:
    app: postiz-redis
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
