apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postiz-container-env
  namespace: postiz
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: postiz-jwt-secret
    - secretKey: DATABASE_URL
      remoteRef:
        key: postiz-database-url
    - secretKey: TEMPORAL_DB_USER
      remoteRef:
        key: postiz-db-username
    - secretKey: TEMPORAL_DB_PASSWORD
      remoteRef:
        key: postiz-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: postiz
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: credentials.json
      remoteRef:
        key: postiz-cloudflare-tunnel
