apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

resources:
  - namespace.yaml
  - repository.yaml
  - storage.yaml
  - release.yaml
  - secrets.yaml
  # - gateway.yaml
  # - routes.yaml
  # - networkpolicy.yaml

configMapGenerator:
  - name: nextcloud-values
    files:
      - values.yaml=values.yaml
    # Add this to force regeneration when content changes
    options:
      disableNameSuffixHash: false
      # Add a label to force regeneration
      labels:
        config-version: "v2"  # Change this to force regeneration

configurations:
  - kustomizeconfig.yaml

