apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

resources:
  - namespace.yaml
  - repository.yaml
  # - storage.yaml
  - gateway.yaml
  - routes.yaml
  - release.yaml
  - networkpolicy.yaml

configMapGenerator:
  - name: nextcloud-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

