apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin-creds
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: nextcloud-admin-username
    - secretKey: password
      remoteRef:
        key: nextcloud-admin-password
---
# Database credentials for PostgreSQL
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-db-creds
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: nextcloud-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: nextcloud-db-username
    - secretKey: password
      remoteRef:
        key: nextcloud-db-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-redis-creds
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: nextcloud-redis-creds
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: redis-password
      remoteRef:
        key: nextcloud-redis-password
