apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc-nfs
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 4Ti
