apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: cloudflare-tunnel-egress
  namespace: linkding
spec:
  endpointSelector:
    matchLabels:
      app: cloudflared
  egress:
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53" 
              protocol: TCP
    
    # Allow Cloudflare edge servers (specific IP ranges)
    - toCIDR:
        - "198.41.200.0/24"    # Cloudflare edge IPs
        - "198.41.192.0/19"
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "104.16.0.0/13"
        - "104.24.0.0/14"
        - "108.162.192.0/18"
        - "131.0.72.0/22"
        - "141.101.64.0/18"
        - "162.158.0.0/15"
        - "172.64.0.0/13"
        - "173.245.48.0/20"
        - "188.114.96.0/20"
        - "190.93.240.0/20"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "443"
              protocol: UDP
            - port: "7844"
              protocol: TCP
            - port: "7844"
              protocol: UDP
    
    # Allow internal cluster communication
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": linkding
            app: linkding
      toPorts:
        - ports:
            - port: "3003"
              protocol: TCP
