apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rocket-chat-container-env
  namespace: rocket-chat
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: MONGO_URL
      remoteRef:
        key: rocket-chat-mongo-url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: rocket-chat
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: credentials.json
      remoteRef:
        key: rocket-chat-cloudflare-tunnel
