apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-weather
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: homepage-weather
  data:
    - secretKey: OPENWEATHER_API_KEY
      remoteRef:
        key: openweathermap-api-key
