apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-config
  namespace: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 1Gi
