apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseer
  namespace: servarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyseer
  template:
    metadata:
      labels:
        app: jellyseer
      annotations:
        cilium.io/gateway: "true"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: jellyseer
          image: fallenbagel/jellyseerr:2.7.3
          ports:
            - containerPort: 5055
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: jellyseer
            - name: media
              mountPath: /media
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 3000m
              memory: 8Gi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: servarr-config-pvc-nfs
        - name: media
          persistentVolumeClaim:
            claimName: servarr-media-pvc-nfs
