apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr

resources:
  - deployment.yaml
  # - release.yaml
  # - repository.yaml
  - service.yaml

configMapGenerator:
  - name: jellyseer-values
    files:
      - values.yaml=values.yaml

# configurations:
#   - kustomizeconfig.yaml
