apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: servarr
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: jellyseerr
      version: "2.6.1"
      sourceRef:
        kind: HelmRepository  # Change from OCIRepository
        name: jellyseerr-chart
        namespace: servarr
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
