apiVersion: v1
kind: Service
metadata:
  name: servarr-jellyseer
  namespace: servarr
spec:
  selector:
    app: jellyseer
  ports:
    - port: 5055
      targetPort: 5055
      protocol: TCP
  type: ClusterIP
