apiVersion: v1
kind: Service
metadata:
  name: servarr-jellyfin
  namespace: servarr
spec:
  selector:
    app: jellyfin
  ports:
    - port: 8096
      targetPort: 8096
      protocol: TCP
  type: ClusterIP
