values:
  image:
    registry: "ghcr.io"
    repository: "fallenbagel/jellyseerr"
    tag: "2.7.1"  # Use the AppVersion from chart
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  strategy:
    type: Recreate
  
  service:
    type: ClusterIP
    port: 80  # Chart default is 80, maps to container port 5055
  
  # Use your existing shared PVC instead of creating a new one
  config:
    persistence:
      name: "servarr-config-pvc-nfs"  # Reference your existing PVC
      accessModes:
        - ReadWriteMany  # Match your existing PVC
  
  podAnnotations:
    cilium.io/gateway: "true"
  
  extraEnv:
    - name: TZ
      value: "America/Los_Angeles"
    - name: LOG_LEVEL
      value: "info"
  
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  nodeSelector: {}
  tolerations: []
  affinity: {}
