apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        policy-type: "app"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:10.11.0-rc3

          securityContext:
              allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: jellyfin-configmap
            # - secretRef:
            #     name: jellyfin-container-env

          ports:
            - containerPort: 8096
              protocol: TCP
            - containerPort: 8920
              protocol: TCP
            - containerPort: 1900
              protocol: UDP
            - containerPort: 7539
              protocol: TCP

          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: jellyfin-cache
              mountPath: /cache
            - name: media
              mountPath: /media

          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 4Gi
              cpu: 2

      restartPolicy: Always

      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc-nfs
        - name: jellyfin-cache
          emptyDir:
            sizeLimit: 20Gi  # Temporary cache, doesn't need persistent storage
        - name: jellyfin-media
          persistentVolumeClaim:
            claimName: jellyfin-media-pvc-nfs
