apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc-nfs
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc-nfs
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 5Ti  
