apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-container-env
  namespace: pgadmin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    template:
      data:
        PGADMIN_DEFAULT_EMAIL: "{{ .email }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .password }}"
        PGADMIN_SETUP_EMAIL: "{{ .email }}"
        PGADMIN_SETUP_PASSWORD: "{{ .password }}"
        PGADMIN_CONFIG_CONFIG_DATABASE_URI: "'postgresql://{{ .dbuser }}:{{ .dbpassword }}@pgadmin-pg.seyzahl.com:5432/pgadmin'"
  data:
    - secretKey: email
      remoteRef:
        key: pgadmin-admin-email
    - secretKey: password
      remoteRef:
        key: pgadmin-admin-password
    - secretKey: dbuser
      remoteRef:
        key: pgadmin-db-username
    - secretKey: dbpassword
      remoteRef:
        key: pgadmin-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: pgadmin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: credentials.json
      remoteRef:
        key: pgadmin-cloudflare-tunnel
