apiVersion: apps/v1
kind: Deployment
metadata:
  name: servarr-qbittorrent
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: servarr-config-pvc-nfs
        - name: media
          persistentVolumeClaim:
            claimName: servarr-media-pvc-nfs
        - name: gluetun-data
          emptyDir: {}
      containers:
        # Gluetun VPN container with YOUR NordVPN settings
        - name: gluetun
          image: qmcgaw/gluetun
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            runAsUser: 0
          env:
            # Core VPN settings - NordVPN with WireGuard
            - name: VPN_SERVICE_PROVIDER
              value: "nordvpn"
            - name: VPN_TYPE
              value: "wireguard"
            
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: gluetun-vpn-config
                  key: WIREGUARD_PRIVATE_KEY
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: gluetun-vpn-config
                  key: WIREGUARD_ADDRESSES 
            
            # Server selection
            - name: SERVER_COUNTRIES
              value: "United States"
            
            # Enable server list updates
            - name: UPDATER_PERIOD
              value: "24h"
            
            # Other settings
            - name: TZ
              value: "America/Los_Angeles"
            - name: HEALTH_SERVER_ADDRESS
              value: ":8000"
          
          ports:
            - containerPort: 8000
              name: health
              protocol: TCP
            - containerPort: 8080
              name: qbittorrent
              protocol: TCP
            - containerPort: 6881
              name: bittorrent-tcp
              protocol: TCP
            - containerPort: 6881
              name: bittorrent-udp
              protocol: UDP
          
          volumeMounts:
            - name: gluetun-data
              mountPath: /gluetun
              subPath: gluetun
          
          livenessProbe:
            httpGet:
              path: /v1/wireguard/status
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /v1/wireguard/status
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
          
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

        # qBittorrent main container
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:5.1.2
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
            - name: WEBUI_PORT
              value: "8080"
          
          # Network through gluetun container
          securityContext:
            runAsUser: 0
          
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: qbittorrent
            - name: media
              mountPath: /media
          
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 5
          
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 10
          
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
