apiVersion: apps/v1
kind: Deployment
metadata:
  name: servarr-qbittorrent
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: servarr-config-pvc-nfs
        - name: media
          persistentVolumeClaim:
            claimName: servarr-media-pvc-nfs
      containers:
        # Gluetun VPN container
        - name: gluetun
          image: qmcgaw/gluetun:v3.40.0
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "nordvpn"
            - name: VPN_TYPE
              value: "openvpn"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: vpn-credentials
                  key: username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vpn-credentials
                  key: password
            - name: SERVER_COUNTRIES
              value: "United States"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          livenessProbe:
            exec:
              command:
                - /gluetun-entrypoint
                - healthcheck
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

        # qBittorrent main container
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:5.1.2
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: web
            - containerPort: 6881
              name: bittorrent-tcp
              protocol: TCP
            - containerPort: 6881
              name: bittorrent-udp
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: qbittorrent
            - name: media
              mountPath: /media
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
