apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-vpn-config
  namespace: servarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: wireguard-private-key
    - secretKey: WIREGUARD_PUBLIC_KEY
      remoteRef:
        key: wireguard-public-key
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: wireguard-address
