apiVersion: v1
kind: Service
metadata:
  name: servarr-qbittorrent
  namespace: servarr
spec:
  selector:
    app: qbittorrent
  ports:
    - port: 8080
      targetPort: 8080
      name: web
      protocol: TCP
    - port: 6881
      targetPort: 6881
      name: bittorrent-tcp
      protocol: TCP
    - port: 6881
      targetPort: 6881
      name: bittorrent-udp
      protocol: UDP
  type: ClusterIP
