# NOTE: These must be set manually to the control plane IP addresses
# kubeEtcd:
#  endpoints:
#    - x.y.z.a
#    - x.y.z.b
#    - x.y.z.c
kubeControllerManager:
  service:
    selector:
      k8s-app: kube-controller-manager
kubeScheduler:
  service:
    selector:
      k8s-app: kube-scheduler

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector:
      matchLabels:
        app.kubernetes.io/component: monitoring

    # Discover all PodMonitors, Probes, PrometheusRules and ServiceMonitors
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  grafana.ini:
    date_formats:
      default_week_start: sunday

  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: monitoring
      provider:
        allowUiUpdates: true

  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 4Gi

  # Allow Omni Workload Proxying for this service
  service:
    annotations:
      omni-kube-service-exposer.sidero.dev/port: "50082"
      omni-kube-service-exposer.sidero.dev/label: Grafana
