apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-container-env
  namespace: minecraft
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: CF_API_KEY
      remoteRef:
        key: minecraft-cf-api
