apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-pvc-nfs
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 30Gi
