apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:GcmjCd5lN3ap0WjeJtH6T8L3uE7jBWbN6nuKARCbu7Z1QSEYZveLlspRzX8XhhDvbF2bWXnP/PiiPAvx8z0bmNT/IS9ycTH5heajsWr5u38K6vM+mvqzmxGxLdJvJs6LVIj19d67v0uOaaTP+1IlH423oZe/Cg858RpwP6unNJJzZti6N7RQH8awcEvXa0vEN7y/LP1C+0opAH5xkgXtw9QVKDyZ/GtA/b6oZx89fkCkqdkM6bBCjn3ZOpheJ5MjxjUwG0SD95u+eXj/ntwy/QhXjvl0XIg5,iv:4xWnR2B4WlW5wpmrvPKNAlKuBqkZg/kfO+5pGNfcgAg=,tag:R0gMKoVNOFgMOpx6OJGK1A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: audiobookshelf-tunnel
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17qckp96wh2mzrd3dge9jrt6hudt40ltj2rgfqk42jgugjq9a94nqv6erff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeTJtNmJYNWNqL1l1MVdC
            N1hRZ0hVVlpNeFNwSHZjQ2xQNXp0RklSZEM0Ckw3SXNNcEVzQnhVWmtCdmR0R3hF
            Y2oyWjB2dTYveVNMRnFtV3cxbzVhVVUKLS0tIEpHNzBpZDByWVp0aEhJZmYvM3hM
            TE9ncHJZV1pYdzhtMlZxZS9Ed2xLeGcKYKkwuU4rMFBCltaMG3gUUKfR2VOgLylm
            BgGYtzX/w2+UtB6bpVvaBHUzFjJc5Bd2i+znb8gaDA04zMEI5hzwzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-03T08:40:43Z"
    mac: ENC[AES256_GCM,data:OWZqTNLiYS4rM8GF7NtGoWAofmoMCGev8hBASnR8z4Qm7yWBfDdRSZyTTeTITZw7ivcBgeOuLBUT3J5Fjve+lizOVnjoBIgd3DANQ+8Vx7aAenPIwE90lsMIXGfIXUDAaj7W0ijq5DLENDmTa5CjMpVNsbbfovov+MWpv55bMAo=,iv:nNNvgpmKD21wBFzvwnuOkzxHHwW9cB0qfE8P7PJsjPU=,tag:VM+apxE73sjDBMyxtf9emQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
