apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        runAsUser: 33 # found from www-data:
        runAsGroup: 33 # found from www-data:
        fsGroup: 33 # found from www-data:
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.37.0

          securityContext:
              allowPrivilegeEscalation: false

          envFrom:
          # - configMapRef:
          #     name: linkding-configmap
            - secretRef:
                name: linkding-container-env

          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
          ports:
            - containerPort: 9090

      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
