apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-redis
  namespace: immich
  labels:
    app: immich-redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich-redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: immich-redis
  template:
    metadata:
      labels:
        app: immich-redis
        app.kubernetes.io/component: cache
        app.kubernetes.io/instance: immich
        app.kubernetes.io/name: immich-redis
        policy-type: "app"
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: redis
          image: redis:8-alpine
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: immich-redis
  namespace: immich
  labels:
    app: immich-redis
    app.kubernetes.io/name: immich-redis
    app.kubernetes.io/instance: immich
    app.kubernetes.io/component: cache
spec:
  selector:
    app: immich-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
