apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-container-env
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: immich-db-username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: immich-db-password
