apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-suwayomi
  namespace: suwayomi
spec:
  selector:
    matchLabels:
      app: cloudflared-suwayomi
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared-suwayomi
        policy-type: "app"
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - --protocol
            - http2
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - containerPort: 2000
              name: http-metrics
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: creds
          secret:
            secretName: cloudflare-tunnel-suwayomi
        - name: config
          configMap:
            name: cloudflared-suwayomi
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-suwayomi
  namespace: suwayomi
data:
  config.yaml: |
    tunnel: suwayomi
    credentials-file: /etc/cloudflared/creds/credentials.json

    metrics: 0.0.0.0:2000

    no-autoupdate: true

    ingress:
    - hostname: suwayomi.seyzahl.com
      service: http://authentik-outpost-suwayomi:9000

    - service: http_status:404
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-suwayomi
  namespace: suwayomi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: credentials.json
      remoteRef:
        key: suwayomi-cloudflare-tunnel
