apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:UyZpwl2K8Eqll5m+Vq+DYbVoUHBp7aV2B7Y4piLVRdLRH7Nj6QSZouS4XPMSJAkpbCYTVR9lfi8=,iv:Wp5nLrf4BNX7ks2szv7DxAiUAcKpN2xBRIJDdVxI4h0=,tag:ArlvrBt4/LpACM3ETnCDCg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-container-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17qckp96wh2mzrd3dge9jrt6hudt40ltj2rgfqk42jgugjq9a94nqv6erff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQk5XYjF6bTNaa21MbnB0
            QXpPeEczVmlmaGkyYUhQMWJxdEw1WStIeVFZCmNDMGRHVzQ1eVFkUlFYSkp1VElp
            Rkx3SVdkejhQcHJiUUUvcVA4VnRUdnMKLS0tIFZhRi9XWVBMNis4OUc5dG1xNkgr
            ckVKK21RYTlTbzhrRHlEWVd3K21QdkUKC3dnRiOWxbNgmT3M2NmpeL+u5l+so+4D
            dPJ6BOoDFjIdBqVL0yYldPN18NQPCLUBAyg58ibq4cQp7+cNo4mSSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-03T04:59:22Z"
    mac: ENC[AES256_GCM,data:GgwixzNgNOa+BTrdn6OAa7H5iTbJfoOPmZhqcTCRbQ0z26mOhnr16KniMNti7WDbc8459JEHKQH1hP9zPvpFGe6i8oiafnY7zfl86HT53e/dqzciL6SDbDEXV8p1ioxfDVZl8GPf7wRwkZC/7I3+PqUxPEy4mHcNo4YQjh0IXaA=,iv:dTulvJesnxtvsRg3GhvIabi2/Q4QHEgjl/0j5+iQbD0=,tag:GXBSaWEagJBYOHiV9Oni3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
