apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed
  template:
    metadata:
      labels:
        app: commafeed
    spec:
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      containers:
      - name: commafeed
        image: athou/commafeed:5.4.0-h2
        ports:
        - containerPort: 8082
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: commafeed-data
            mountPath: /commafeed/data
      volumes:
        - name: commafeed-data
          persistentVolumeClaim:
            claimName: commafeed-data-pvc
