apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed

  template:
    metadata:
      labels:
        app: commafeed
        try: "0"
        policy-type: "app"

    spec:
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 3000
      #   fsGroup: 2000

      containers:
        - name: commafeed
          image: athou/commafeed:5.4.0-h2-jvm

          # securityContext:
            # allowPrivilegeEscalation: false

          envFrom:
          - configMapRef:
              name: commafeed-configmap
            # - secretRef:
            #     name: commafeed-container-env

          # volumeMounts:
          #   - name: commafeed-data
          #     mountPath: /commafeed/data


    restartPolicy: Always
